baseURL = "https://arayan.in/"
languageCode = "en-us"
title = "Arayanâ€™s Paati"

theme = "ananke"

[permalinks]
  newsletter = "/newsletter/:slug/"

[params]
  description = "Notes on growth, product, psychology, and AI"
