baseURL = "https://arayan.in/"
languageCode = "en-us"
title = "Arayan"

[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke"

[permalinks]
  newsletter = "/newsletter/:slug/"
