baseURL = "https://arayan.in/"
languageCode = "en-us"
title = "Arayan's Flywheel"

theme = "ananke"

[permalinks]
  newsletter = "/newsletter/:slug/"

[params]
description = "Weekly Pill of Growth & Tech"
